jobs:
  allow_failures:
    - rust: nightly
  include:
    - language: python
      python: 3.8
      before_script:
        - cd python
      script:
        - pytest
        - mypy 1 2 3

    - language: rust
      rust: stable
      cache: cargo
      before_script:
        - cd rust
    - language: rust
      rust: beta
      cache: cargo
      before_script:
        - cd rust
    - language: rust
      rust: nightly
      cache: cargo
      before_script:
        - cd rust
